/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DelegatesFocus {
    }
    interface NoDelegatesFocus {
    }
}
declare global {
    interface HTMLDelegatesFocusElement extends Components.DelegatesFocus, HTMLStencilElement {
    }
    var HTMLDelegatesFocusElement: {
        prototype: HTMLDelegatesFocusElement;
        new (): HTMLDelegatesFocusElement;
    };
    interface HTMLNoDelegatesFocusElement extends Components.NoDelegatesFocus, HTMLStencilElement {
    }
    var HTMLNoDelegatesFocusElement: {
        prototype: HTMLNoDelegatesFocusElement;
        new (): HTMLNoDelegatesFocusElement;
    };
    interface HTMLElementTagNameMap {
        "delegates-focus": HTMLDelegatesFocusElement;
        "no-delegates-focus": HTMLNoDelegatesFocusElement;
    }
}
declare namespace LocalJSX {
    interface DelegatesFocus {
    }
    interface NoDelegatesFocus {
    }
    interface IntrinsicElements {
        "delegates-focus": DelegatesFocus;
        "no-delegates-focus": NoDelegatesFocus;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "delegates-focus": LocalJSX.DelegatesFocus & JSXBase.HTMLAttributes<HTMLDelegatesFocusElement>;
            "no-delegates-focus": LocalJSX.NoDelegatesFocus & JSXBase.HTMLAttributes<HTMLNoDelegatesFocusElement>;
        }
    }
}
